Made several improvements to the "call times" section of the "staff"
sharett/hotline pull request #26
Opened 2017-11-06 15:22 UTC by misplacedpriorities

Made several improvements to the "call times" section of the "staff"
page:

(1) Changed existing display of call times by breaking the various
    fields into multiple columns, one per field, for readability
    purposes.
(2) Changed existing display of call times to only display a given
    value if it is different from the previous row's value in the
    same column, or they are the same, but a value for this row to
    the left of this one was found to be different from the value
    in that column in the row above.
(3) Also made display of "receive call alerts"-only entries in the
    call times be dark red, to visually differentiate it from other
    entries for the user.
(4) Added a drop-down selector on the staff page allowing the choice
    of showing the call times sorted by user name (the old way), or
    sorted by day.
(5) Added an edit icon for all call times that reuses the existing
    "add call time" modal dialog to allow the user to edit an
    existing call time.
(6) Changed the modal dialog to use checkboxes for all the language
    choices, so that when a new call time is added, an entry is made
    in the call_times table for each language the user chose.
(7) Broke the add/edit call time modal dialog out into a new file,
    and separated functionality for the different ways of displaying
    call times into their own files as well. Also created a utility
    function file to hold common functions.
(8) Fixed a few PHP Notice log messages saying that variables were
    undefined in order to declutter the logs.

2017-11-08 20:10 UTC, sharett requested changes
Thanks Chris - I love the new look, and the extensive commenting.  One major problem - you can't add any call time entries.  Also, there is no way to add entries from the chronological display - was this intentional?  Perhaps a "+" button should be next to all pencil icons?

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_alpha.php
> +        <td></td><td></td><td></td><td></td><td></td><td>
Instead of multiple td opening and closing tags, you could instead use:
`<td colspan="#"></td>`

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_chrono.php
> +                // Copy he multi-day result, then insert into it
"Copy the"

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_chrono.php
> +                // valuesfor the 'day_of_week' and 'day_ordinal'
"values for"

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_chrono.php
> +/**
The pure SQL function is quite easy to read and understand, and only slightly slower.  The majority of the time in loading the page is actually from querying Twilio for the active calls.  I'd propose moving that out of this page, to speed up the page load.

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_modal.php
> +          <button type="submit" class="btn btn-primary">Add</button>
Change "Add" to "Edit" when editing entires?

2017-11-08 20:10 UTC, sharett commented on hotline_call_times_utils.php
> +    $texts = (isset($call_time['texts']) && ($call_time['texts'] == 'on'));
Adding a call time always fails, as the form fields are "receive_texts", "receive_calls" and "receive_call_answered_alerts".

2017-11-08 20:37 UTC, misplacedpriorities commented
Hi Alex,

Thanks for the quick turnaround on the reviewing process! I am embarrassed that the adding of call times always fails -- I had tested that, but must've refactored something after the last testing, which is not of course kosher. :-/ I'll fix that and the other issues sometime this evening when I'm done with work.

One quick question that I'll ask now in order to speed up the process: When you suggest moving the querying Twilio for the active calls out of the hotline_staff.php page, are you suggesting filling them in asynchronously? I am certainly not opposed to that, but figure it should be something we do under another ticket. Or are you just saying we should move the query of active calls to its own file for some other reason? I ask because it seems to me like every time this page is loaded, that query will have to be performed, whether we have the Twilio-querying code into another file or not. But I may well be wrong about that -- could you explain a bit more? (Within the GitHub pull request review section is fine too.)

Thanks!
Chris

On November 8, 2017 3:10:05 PM EST, Alex Jarrett <notifications@github.com> wrote:
>sharett requested changes on this pull request.
>
>Thanks Chris - I love the new look, and the extensive commenting.  One
>major problem - you can't add any call time entries.  Also, there is no
>way to add entries from the chronological display - was this
>intentional?  Perhaps a "+" button should be next to all pencil icons?
>
>> +            "WHERE contact_id='{$contact['id']}' ".
>+            "ORDER BY call_times.day, call_times.earliest,
>call_times.latest, ".
>+            "languages.language, call_times.enabled";
>+    if (!db_db_query($sql, $call_times, $error)) {
>+        echo $error;
>+    } ?>
>+      <tr>
>+        <td><?php echo $contact['contact_name']?></td>
>+        <td><?php echo getContactNumber($contact['phone']); ?></td>
>+        <?php
>+
>+    // Allow removal of staff entry if all call time records are
>+    // removed.
>+    if (count($call_times) == 0) {
>+        ?>
>+        <td></td><td></td><td></td><td></td><td></td><td>
>
>Instead of multiple td opening and closing tags, you could instead use:
>`<td colspan="#"></td>`
>
>> +    // Iterate through the multi-day results, adding each in turn
>+    // to the single-day results list once for every day it
>+    // represents. Thus, an 'all' result is added seven times, once
>+    // for each day of the week; a 'weekends' result is added two
>+    // times, one per weekend day; and so on.
>+    foreach (array(
>+        "all" => array("Sun" => 0, "Mon" => 1, "Tue" => 2, "Wed" => 3,
>+                        "Thu" => 4, "Fri" => 5, "Sat" => 6),
>+        "weekends" => array("Sun" => 0, "Sat" => 6),
>+        "weekdays" => array("Mon" => 1, "Tue" => 2, "Wed" => 3,
>+                        "Thu" => 4, "Fri" => 5)
>+    ) as $grouping => $days) {
>+        foreach ($multiDayResults[$grouping] as $multiDayResult) {
>+            foreach ($days as $day => $ordinal) {
>+
>+                // Copy he multi-day result, then insert into it
>
>"Copy the"
>
>> +    // to the single-day results list once for every day it
>+    // represents. Thus, an 'all' result is added seven times, once
>+    // for each day of the week; a 'weekends' result is added two
>+    // times, one per weekend day; and so on.
>+    foreach (array(
>+        "all" => array("Sun" => 0, "Mon" => 1, "Tue" => 2, "Wed" => 3,
>+                        "Thu" => 4, "Fri" => 5, "Sat" => 6),
>+        "weekends" => array("Sun" => 0, "Sat" => 6),
>+        "weekdays" => array("Mon" => 1, "Tue" => 2, "Wed" => 3,
>+                        "Thu" => 4, "Fri" => 5)
>+    ) as $grouping => $days) {
>+        foreach ($multiDayResults[$grouping] as $multiDayResult) {
>+            foreach ($days as $day => $ordinal) {
>+
>+                // Copy he multi-day result, then insert into it
>+                // valuesfor the 'day_of_week' and 'day_ordinal'
>
>"values for"
>
>> +                // results.
>+                $result = $multiDayResult;
>+                $result["day_of_week"] = $day;
>+                $result["day_ordinal"] = $ordinal;
>+                $call_times[] = $result;
>+            }
>+        }
>+    }
>+
>+    // Sort the results to complete the merge.
>+    usort($call_times, "compareCallTimesChronologically");
>+
>+    return $call_times;
>+}
>+
>+/**
>
>The pure SQL function is quite easy to read and understand, and only
>slightly slower.  The majority of the time in loading the page is
>actually from querying Twilio for the active calls.  I'd propose moving
>that out of this page, to speed up the page load.
>
>> +                    ?>> calls
>+            </label>
>+            <label class="checkbox-inline">
>+              <input type="checkbox" id="calltime_answered_alerts"
>+                    name="call_time[receive_call_answered_alerts]"
>+                    <?php
>+                       
>echo($call_time['receive_call_answered_alerts'] == "y" ? " checked" :
>"")
>+                    ?>> call answered alerts
>+            </label>
>+          </div>
>+        </div>
>+        <div class="modal-footer">
>+          <a class="btn btn-default"
>+                href="hotline_staff.php?display_type=<?php echo
>$display_type ?>"
>+                role="button">Close</a>
>+          <button type="submit" class="btn btn-primary">Add</button>
>
>Change "Add" to "Edit" when editing entires?
>
>> +    // list of languages
>+    $languages = array();
>+    foreach ($call_time_languages as $language => $include) {
>+        if ($include == 'on') {
>+            $languages[] = $language;
>+        }
>+    }
>+    if (count($languages) == 0) {
>+        $error = "The call time record could not be added because no
>".
>+                "language was specified.";
>+        return false;
>+    }
>+
>+    // Ensure at least one checkbox is selected (for texts, calls, or
>+    // answered alerts.
>+    $texts = (isset($call_time['texts']) && ($call_time['texts'] ==
>'on'));
>
>Adding a call time always fails, as the form fields are
>"receive_texts", "receive_calls" and "receive_call_answered_alerts".

2017-11-08 22:22 UTC, sharett commented
The query for active calls is unrelated to the editing of staff entries.  We are just using this page as a place to display it.  Since it adds an appreciable delay, moving it to another page (perhaps a hotline tab) which people could view and reload as needed would speed things up for both pages.  Asynchronous loading that automatically refreshes would probably be great for that page, and not difficult to implement.

2017-11-09 00:21 UTC, misplacedpriorities commented on hotline_call_times_alpha.php
> +        <td></td><td></td><td></td><td></td><td></td><td>
Good point, I had forgotten about spanning columns. Fixed in various files in next patchset.

2017-11-09 00:21 UTC, misplacedpriorities commented on hotline_call_times_chrono.php
> +                // Copy he multi-day result, then insert into it
Will do.

2017-11-09 00:22 UTC, misplacedpriorities commented on hotline_call_times_chrono.php
> +                // valuesfor the 'day_of_week' and 'day_ordinal'
Will do.

2017-11-09 00:23 UTC, misplacedpriorities commented on hotline_call_times_chrono.php
> +/**
Will do -- there will be a fifth page in the tabs, "Active Calls".

2017-11-09 00:23 UTC, misplacedpriorities commented on hotline_call_times_modal.php
> +          <button type="submit" class="btn btn-primary">Add</button>
Will do.

2017-11-09 00:23 UTC, misplacedpriorities commented on hotline_call_times_utils.php
> +    $texts = (isset($call_time['texts']) && ($call_time['texts'] == 'on'));
Oops. Will fix.

2017-11-09 00:25 UTC, misplacedpriorities commented
Thanks, Alex, for explaining further -- I hadn't understood that you wanted the entire display (not just the query) of active calls moved to a new file. The next patchset (coming very shortly) has them as a fifth tab (displacing the existing four tabs to the right) called "Active Calls".

2017-11-12 20:40 UTC, sharett commented
Looks great, thanks for the fast turnaround.  I just have one minor user interface suggestion, to move the plus sign (Add a call time for this staff member) to the right side of the actions column, and standardize it so it looks the same on the "by day" and "by name" modes.  How does that sound?

2017-11-12 21:35 UTC, misplacedpriorities commented
I can do that! But before I do, one question:

I placed the buttons that way because of precedent; I see a lot of "Add, Edit, Delete" arrangements of action buttons in other GUIs. Would you be happy with instead unifying the UI by (instead of changing the arrangement in the "By Day" display) changing "By Name" to have an "Add" button next to every row, instead of below the set of all rows for a specific staff members?

That way, each row, regardless of which type of display is being shown, will have "Add, Edit, Delete" next to it. (Eventually that will even be true for the staff-only lines in "By Name", since I believe one of outstanding issues is adding editability for an existing staff member.)

The advantage in my mind is the symmetry of it. Disadvantage: It involves the changing of an existing GUI arrangement (in "By Name"), so users will have to spend a tiny bit of extra brain power discovering the new GUI. I see that as not particularly problematic since they are going to have to get used to a new "By Name" display anyway (with the extra columns, etc.), but that's just me.

I'm happy whichever way you want to go on this. Let me know and I'll make the change.

2017-11-13 02:21 UTC, sharett commented
Yes, fine with it either way.  Part of me thought that because the add creates a new one, while the edit and delete affect the current line, that having the edit/delete closer would be more intuitive.  But I'm not sure that is really true.  I do like the idea of a unified UI for both by day and by name.

2017-11-13 03:00 UTC, misplacedpriorities commented
OK, I put the "add" button to the left of the "edit" and "delete" buttons in each row of the "By Name" view.

2017-11-13 03:02 UTC, sharett approved these changes

2017-11-13 03:02 UTC, merged