Test branch
sharett/hotline pull request #5
Opened 2017-04-01 14:31 UTC by sharett

Hi again Wouter and Bassam - I made some additional commits, and I wasn't sure how to update the old pull request so I made this new one.

2017-04-03 01:48 UTC, jakeschievink requested changes
Just some naming issues I had. I just gave it a look over, I'll try and give it a thorough test tomorrow.

2017-04-03 01:48 UTC, jakeschievink commented on database_schema.sql
> +CREATE TABLE `blocks` (
I would name this table a different name. I think blocks is too ambiguous and blocked_numbers would convey alot more

2017-04-03 01:48 UTC, jakeschievink commented on database_schema.sql
> +  `digit` int(1) UNSIGNED NOT NULL,
I think digit is too ambiguous as well. Perhaps dial_number? I'm actually having a hard thinking of a good rename all I know is that "digit" hard to understand.

2017-04-03 01:48 UTC, jakeschievink commented on database_schema.sql
> +  `digit` int(1) UNSIGNED NOT NULL,
maybe menu_number?

2017-04-03 01:48 UTC, jakeschievink commented on hotline_blocks.php
> +function addBlock($phone, &$error, &$message)
Id rename to addBlockedNumber

2017-04-04 22:37 UTC, bkurdali commented on database_schema.sql
> +  `digit` int(1) UNSIGNED NOT NULL,
I could change this, let's think : keypress ? digitpressed?

2017-04-05 00:24 UTC, bkurdali commented on lib/lib_sms.php
> +	$statuses = array("queued", "ringing", "in-progress");
Is it possible to get the array values from the twilio api? would be DRYer, not a blocker for merging

2017-04-05 00:34 UTC, bkurdali commented on README.md
> +* Install a database editing utility such as PhpMyAdmin and place it in a directory under the main directory.
Looks like this clobbered a desired change (reverting back to the sanctdb directory) ?

2017-04-05 00:53 UTC, sharett commented on lib/lib_sms.php
> +	$statuses = array("queued", "ringing", "in-progress");
Sorry I don't really understand.  These are the status values that we want to retrieve from the Twilio API.   There are more status values, but they are for completed calls.

2017-04-05 00:56 UTC, sharett commented on README.md
> +* Install a database editing utility such as PhpMyAdmin and place it in a directory under the main directory.
No, I changed it back.  I realized that it needs to be called "sanctdb" for now as that is the name in .gitignore

2017-04-07 13:23 UTC, sharett commented on database_schema.sql
> +  `digit` int(1) UNSIGNED NOT NULL,
How about menu_selection?

2017-04-17 18:02 UTC, merged