Play media instead of robot speak
sharett/hotline pull request #8
Opened 2017-04-29 13:45 UTC by jakeschievink

2017-04-30 00:42 UTC, sharett requested changes
Nice! Just a couple of problems I noted.

2017-04-30 00:42 UTC, sharett commented on lib/lib_sms.php
> +        if (!$voice_code) $voice_code = 'en';
The English voice code we are using is "en-US" - should this be the default?

2017-04-30 00:42 UTC, sharett commented on lib/lib_sms.php
> +*   The queue's to retrieve's "friendlyName"
This description is not accurate, and the other variables aren't documented.

2017-04-30 00:42 UTC, sharett commented on twin/incoming-voice.php
> +    sms_playOrSay($gather, $language['prompt'], language['twilio_code']);
language['twilio_code'] is missing a $

2017-05-02 15:07 UTC, jakeschievink commented on twin/incoming-voice.php
> +    sms_playOrSay($gather, $language['prompt'], language['twilio_code']);
done

2017-05-02 15:08 UTC, jakeschievink commented on lib/lib_sms.php
> +        if (!$voice_code) $voice_code = 'en';
I think it should be for now until otherwise noted. But what do you think?

2017-05-02 15:09 UTC, jakeschievink commented on lib/lib_sms.php
> +*   The queue's to retrieve's "friendlyName"
done

2017-05-06 02:21 UTC, sharett requested changes

2017-05-06 02:21 UTC, sharett commented on twin/handle-screen.php
> +		sms_playOrSay($gather, $HOTLINE_CONNECTING_TO_CALLER);
This should be $response instead of $gather.

2017-05-06 02:21 UTC, sharett commented on twin/voicemail-record.php
> +	$response->sms_playOrSay('An error occurred - your voicemail was not received. Goodbye.',
This should be "sms_playOrSay($response," instead of "$response->sms_playOrSay("

2017-05-06 02:21 UTC, sharett commented on twin/voicemail-record.php
> +		$response->sms_playOrSay('An error occurred - your voicemail was not received. Goodbye.');
This should be "sms_playOrSay($response," instead of "$response->sms_playOrSay("

2017-05-06 02:21 UTC, sharett commented on twin/voicemail-record.php
> +		$response->sms_playOrSay($language['voicemail_received'],
This should be "sms_playOrSay($response," instead of "$response->sms_playOrSay("

2017-05-06 22:41 UTC, bkurdali commented
I don't have any objections to this! (except for sharett's changes which seem correct)

2017-05-08 01:42 UTC, sharett approved these changes
Looks good!

2017-05-15 01:56 UTC, merged